version: '3.8'
services:
  app:
    image: ubuntu
    volumes:
      - app:/app
      - app1:/app1
    working_dir: /app
    stdin_open: true
    tty: true
    command: tail -F anything
  
  backup:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/tmp/backups/app:ro
      - app1:/tmp/backups/app1:ro
      - ./outputs:/tmp/outputs
      # save logs to host
      
    environment:
      - BACKUP_DIR=/tmp/backups
      - OUTPUT_DIR=/tmp/outputs
      - S3_ENDPOINT=https://0c5059a262cdf86340651b0d9a085c9e.r2.cloudflarestorage.com
      - S3_BUCKET=backups
      - S3_ACCESS_KEY=a37a6cd9f857e427818e7aae139689e4
      - S3_SECRET_KEY=7d8ab79a602a5a236d12e6e3e4bd6339665feea70f187775ff8d1914236e9eab
      - S3_PREFIX=docker
      - SECOND_INTERVAL=60    
    
    
volumes:
  app:
  app1: