version: "3.8"
services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests/app:/tmp/backups/app:ro
      - ./tests/output:/tmp/output
    environment:
      - BACKUP_DIR=/tmp/backups
      - OUTPUT_DIR=/tmp/output
      - S3_ENDPOINT=
      - S3_BUCKET=backups
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_PREFIX=docker-volumes-backup
      - SECOND_INTERVAL=60
